- src/app/components/Book/Book.jsx
- src/app/components/BookList/BookList.jsx
- src/app/utils/utils.js
Fixes #25 
Adds "AND" filtering. Example below based on not-so-good available data:
You can try clicking on `adventure` `fantasy` `friendship` `funny`, in any order, and you should get that one book as a result "Pugs of the Frozen North...". If you do not get any results from a filter, it's because the data is not right - those tags there are not necessarily the tags we will used but are hardcoded until we get the right dataset.
> Filter 'and' logic

- src/app/actions/BookActions.js
- src/app/components/Application/Main.jsx
- src/app/components/BookFilters/BookFilters.jsx
- src/app/components/BookFilters/Filter.jsx
- src/app/components/BookList/BookList.jsx
- src/app/components/Sidebar/Sidebar.jsx
- src/app/stores/BookStore.js
- src/app/utils/utils.js
- src/server/routes/annualData.js
Fixes #26 Big PR:
* Removes re-useable functions and puts them in `utils`.
* Removes Action calls and instead triggers function calls up to the parent `Main` component.
* This is useful to keep track of both the filtered book item array and the filtered filter array.
* Clicking on a filter updates the SVG and also triggers the focus on them AFTER they get rendered since we want to keep track of what was selected/deselected for a11y purposes.
> Removing not available filters

- index.js
- package.json
This small PR focuses on removing NPM packages we currently don't need. As needs arise, we should first think about really adding more dependencies and then add to the appropriate section (`devDependencies` vs `dependencies`)
Ideally I would like to setup AWS to run `npm install --production` to improve the install process on deployments.
Fixes #38 
CC: @kfriedman @EdwinGuzman
> updated package.json and source to remove unused packages

- package.json
- server.js
- react-doc-meta is outdated since React 0.13ish and does not incorporate PropTypes module, removed from dependencies.
- used appConfig metaTags array to render server-side.
- Tested in production mode, see screenshot
Fixes #37 
CC: @RobKelley
> Removed react-doc-meta npm module which was the culprit

- src/app/components/Sidebar/Sidebar.jsx
- test/unit/Sidebar.test.js
Fixes #64 
* The SVG icon now reads "Return to"
* The link is surrounded in a `<nav>` element.
> Updating the left sidebar 'back' link to be a nav.

- appConfig.js
- src/app/components/Hero/Hero.jsx
This PR addresses #59 and #60. It:
- Removes the "category" heading
- Changes the main header to a `h1`.
- Updates the main header copy
> Hero accessibility

- appConfig.js
- server.js
- src/server/routes/annualData.js
- src/server/views/index.ejs
Fixes #67 
The page's title should now read either "Best Books for Teens" or "Best Books for Kids".
> Updating the page's title based on the route.

- src/server/helper/kmsClientHelper.js
- src/server/helper/nyplApiClient.js
- src/server/helper/nyplApiClientHelper.js
Please check out the `kmsClientHelper.js` file. The ultimate goal is to make that file into a separate npm package.
Why? Because this same process is being used in Staff Picks and in Discovery.
Context:
We are using the [@nypl/nypl-data-api-client](https://www.npmjs.com/package/@nypl/nypl-data-api-client) and passing in each app's own client id and client secret (and oauth url) in order to make requests to the API.
The only issue is that we want to use encrypted versions of the client id and client secret as environment variables in AWS Elastic Beanstalk. In order to encrypt and decrypt, we are using AWS's KMS feature.
In AWS EB:
- Each app reads the encrypted environment variables,
- KMS decrypts the strings and instantiates the `nyplDataApiClient`,
- That client is stored and used to …
> Api kms client

- src/app/components/BookFilters/BookFilters.jsx
- src/app/components/BookFilters/Filter.jsx
Check this one out. I set it up to 2000s to test and when you click on a button and then click on the clear filters button, no unexpected behavior occurs.
Seems to be working okay.
> Clear timeout

- src/app/components/BookFilters/BookFilters.jsx
- src/client/styles/components/_bookFilters.scss
- src/client/styles/utils/_mixins.scss
Fixes #36 
Assigns proper `aria-expanded` attribute to collapsible state.
Uses class based declarations to expand/collapse
Updates to styles for filter buttons, clear button and overall grid container
PS: I need to write tests, which I hope it can be another ticket... @EdwinGuzman -- if you are fine with that then I can create an issue for next Sprint (else I will add tests to this PR)
> Toggable filters

- src/app/components/BookFilters/BookFilters.jsx
Fixes #115 
I removed the span and used the `aria-label` in the `ul` itself. Another option that @wlla suggested was using the h2 'Filter by Tags' label as the label for the `ul`. Which do you think is better, @courtneymcgee ?
This is up on prod: http://staff-picks-production.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/ya
> Removing aria-labelledby and using aria-label for the filter list.

- src/client/styles/components/_bookFilters.scss
@chrismulholland brought this up. If you set a max-height, not all the filters will show. This is an issue on mobile [childrens](http://staff-picks-dev.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/childrens) but not [ya](http://staff-picks-dev.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/ya).
> Removing max-height.

- src/app/components/BookFilters/BookFilters.jsx
- src/app/components/Sidebar/Sidebar.jsx
- test/unit/Sidebar.test.js
Fixes the add-on to #113  - updating how "return to" is associated to the SVG in the breadcrumbs.
Currently on dev, @wlla  please review on PC, thanks!
> Breadcrumb text

- src/app/components/Book/Book.jsx
- src/app/components/Sidebar/Sidebar.jsx
- src/client/styles/components/_hero.scss
- test/unit/Sidebar.test.js
> Adding aria-label to book request links to read out the full item's title

- src/client/styles/components/_bookFilters.scss
Fixes (hopefully) #128 
I just add less space to the left of the h2 and the span. The ^ and down arrow button overlaps the text since it's positioned absolute. Let me know if this works.
> Chopped off mobile text

- src/app/components/BookFilters/Filter.jsx
- src/client/styles/utils/_mixins.scss
- src/client/styles/utils/_utils.scss
This PR uses the same header we have but removes the `.visuallyHidden` css rule from the app and relies on the one set from Design Toolkit. I'm not sure why we have two different sets but we should just use the DT rule.
This solves the problem of the NYPL Logo and the Locations link not being tappable on VO on mobile devices. The only issue is how the VO focus wraps the element. It should be address but I'm not sure how to start that and I think @ricardoom mentioned it could be the SVG box (?).
Related Header tickets: [HDR-21](https://jira.nypl.org/browse/HDR-21) [HDR-12](https://jira.nypl.org/browse/HDR-12)
Currently up on dev: http://staff-picks-dev.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/ya
> Removing visually hidden css from the app.

- test/unit/utils.test.js
This PR improves the previous unit tests for `utils/focusOnFirstAvailableElement`. It breaks the second tests down to several smaller tests with better descriptions. The checks now better examine the return values of the iteration and include the last call for focus().
> Improve test for focus on first available element

- .gitignore
- appConfig.js
- src/app/components/ListSelector/ListSelector.jsx
- src/app/utils/DateService.js
- src/app/utils/utils.js
- src/server/routes/monthData.js
- test/unit/DateService.test.js
- test/unit/ListFilter.test.js
- test/unit/ListSelector.test.js
- test/unit/Main.test.js
- test/unit/ModelListOptionsService.test.js
These help to resolve issues #200 and #201. #200 is a simple lable change for the annual lists for Sidebar dropdowns. Should display 'Year' instead of 'Season.'
Changes for issue #201 requires coordination in updating the metadata for lists on the ingester side. Once the year-month pattern for lists is available in the API, the direct links and redirects should work. 
To test, start your local instance using APP_ENV=production. The new pattern is deployed there for staff-picks lists. There are 2 lists there that you can use to test the code changes within this PR.
> Year month and selector changes

- server.js
- src/server/views/index.ejs
Uncomments the server.js section for re-routing best-books/ to best-books.
Adds baseUrl to the <script> tag for js assets in index.ejs for non-local environments.
> Add slash redirect; fix for js assets path

- src/server/routes/monthData.js
Fixes an issue with log message variables being passed incorrectly for monthData.selectMonthData. Season matches were being passed down to the log which, when invalid, caused an error instead of redirecting to a 404. Audience was also updated here to pass the requested value.
> Fixes #225; fix invalid variable values for log messages

- package.json
- src/app/components/About/About.jsx
- src/app/components/Error404Page/Error404Page.jsx
- src/app/components/ListTitle/ListTitle.jsx
- src/app/utils/utils.js
- src/client/styles/components/_topHeading.scss
- test/unit/About.test.js
- test/unit/Error404Page.test.js
- test/unit/utils.test.js
Corresponds to the adjustments requested as part of https://jira.nypl.org/browse/WWW-317
* Adds line with link to Staff Picks on the 404 page template
* Includes more text in the About page link to print formats
* Updates titles to use `Adults` and `Young Adults` plural forms
** was necessary to add some CSS to adjust for longer titles so the # found would not wrap
** see: http://localhost:3001/books-music-movies/recommendations/best-books/staff-picks/2015-09?audience=YA
** reset _top_heading.scss `h2#list-title` to use the default `font-size: 1.6em` and remove `letter-spacing: -0.3px` in order to trigger the wrapping
** wrapping occurs on lists for Young Adults with Summer, September, October, November in the title.
** CSS change fixes for the longest case of September
> 404, about, and title changes

- src/app/components/About/About.jsx
- src/app/components/Error404Page/Error404Page.jsx
- src/client/styles/components/_topHeading.scss
- test/unit/About.test.js
* Reverted a change to the scss to avoid wrapping the "Books Found" portion on longer titles as per Ricardo's recommendation
* Removed the aria-label added to the 404 page line linking back to the Staff Picks main page
* Updated the text for additional information in the About.jsx component as per copy changes in [WWW-299](https://jira.nypl.org/browse/WWW-299)
> Adjustments for 404 and About components

- src/client/styles/main.scss
Normalize screws up the footer social media icons only on this app so I made this PR in the repo instead of the footer package.
dev: http://staff-picks-development.us-east-1.elasticbeanstalk.com/books-music-movies/recommendations/best-books/staff-picks
> Small CSS override to the footer list item.

- CHANGELOG.md
- package.json
This PR just updates the header to 2.4.9. Can be reviewed on dev
https://dev-www.nypl.org/books-music-movies/recommendations/best-books/staff-picks
The main change should be the visible focus outline styles. It should be dark blue color with shadows
as the screenshot shows
> Updated header to 2.4.9
