appConfig.js
server.js
src/server/routes/annualData.js
src/server/routes/monthData.js
src/server/routes/routes.js

This is an attempt to break out all the functions in the old `ApiRoutes` into cleaner and separate "month/season" and "annual" data fetching functions. Those functions are associated to Express routes and I tried to make that more obvious.

Breaking up server Express routes functions.

---

src/app/components/BookList/BookList.jsx

I noticed that the BookList component was assigning constants and relying on prop checking inside the filtering logic. This quick PR isolates the logic to use functions and filter on function params. In the event we have time to test, it will be a lot easier to test with functions and using params. I Also think that the renderBookItems function might return another component or DOM that displays to the user that the selected filter returns no matches?

Update booklist component to use reusable testable functions

---

.gitignore
src/client/styles/components/_bookFilters.scss
src/client/styles/components/_filter.scss

:meat_on_bone: just removed the drop shadow from the filter module. I've removed it from the designs as well. We'll want to put it only on the mobile version... i'll need guidance on how we want to approach the necessary media queries to its rendered in the right context

emoved the drop shadow... now add it back

---

.ebextensions/00_environment.config
.ebextensions/01_cloudwatch_agent_config.config
.ebextensions/02_enable_log_streaming.config
.ebextensions/node-settings.config
.gitignore
package.json
readme.md

This PR:
* adds the AWS EB config files
* updates the .gitignore file to ignore .elasticbeanstalk config
* updates the README.md with the updated AWS workflow
Fixes #3

Added necessary aws eb configuration files 

---

src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookFilters/Filter.jsx
test/unit/BookFilters.test.js
test/unit/Filter.test.js

Adding unit tests for the `Filter` component and tidying up the component itself based on the tests.

Adding tests for the Filter component.

---

appConfig.js
src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookFilters/Filter.jsx
src/app/components/Sidebar/Sidebar.jsx
src/client/styles/components/_sidebar.scss
test/unit/BookFilters.test.js
test/unit/Filter.test.js
test/unit/Sidebar.test.js

Fixes #42 
The link is hidden on mobile and appears again after the 966px breakpoint.

Updating the breadcrumb back link and writing tests for the Sidebar component.

---

package.json
src/app/stores/BookStore.js
test/unit/Alt.test.js

Added npm script to run the coverage report, open browser and display HTML report.

Updated unit test to include isJsEnabled property.

---

src/app/components/Application/Main.jsx
src/app/components/BookList/BookList.jsx
test/unit/Alt.test.js
test/unit/Application.test.js
test/unit/BookList.test.js
test/unit/Hero.test.js
test/unit/Main.test.js

Wrote more tests, cleaned some old ones up, and added a skeleton test file for the `Hero` component for @kfriedman to add tests to.

Tests tests tests

---

src/app/components/Book/Book.jsx
src/client/styles/components/_bookItem.scss
test/unit/Book.test.js

- cleans up book component
- adds unit tests for book component
- adds strict checking for undefined properties
- modified title tag to h3 and removed link -- fixes #59 bullet (3) CC: @wlla @ricardoom

Unit test book item

---

appConfig.js
src/app/components/Book/Book.jsx
test/unit/Book.test.js

- Fixes the text value for the request links
- Moves from hardcoded strings to config file declaration
- Updated test to pass 100%
Fixes #81

Adjust request buttons text

---

readme.md

Let me know if this makes sense. Thanks.

Adding readme for using kms env variables.

---

src/client/styles/components/_bookFilters.scss

Fixes #80 - styling for the clear filters button.

Updating the clear button style.

---

src/app/components/Application/Application.jsx
src/app/components/Hero/Hero.jsx
src/client/styles/components/_hero.scss

Fixes #92 
Don't want to override what's on dev so here are some screenshots. Pull the branch to check it out on mobile/desktop.

Updating DOM and CSS for the mobile hero version.

---

src/app/components/Book/Book.jsx
src/app/components/BookList/BookList.jsx
src/client/styles/components/_bookItem.scss

Fixes the first checkbox in #98 - the flickering of the tags in the book item card.
Currently up on dev.

Fading card tags

---

src/app/components/Book/Book.jsx
src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookFilters/Filter.jsx
test/unit/Book.test.js

Fixes all checkboxes in #104 
@wlla is having a `<span>` outside of the `<ul>` good enough to associate them together?

Updating words throughout the app.

---

src/client/styles/components/_bookFilters.scss

This PR fixed the issue noted by @chrismulholland on #110 
Minor css updates to avoid overlap on a very specific range of viewport widths...

Fix book count overlay issue

---

src/app/components/About/About.jsx
src/app/components/Book/Book.jsx

Fixes #113 
This is up on dev http://staff-picks-dev.us-east-1.elasticbeanstalk.com/books-music-dvds/recommendations/best-books/ya

Social media a11y

---

src/app/components/BookFilters/BookFilters.jsx

Fixes #119 
Updates string text representation for state of accordion, using text given by @courtneymcgee

updated a11y text for collapsible filter button

---

src/client/styles/components/_bookFilters.scss
src/client/styles/components/_filter.scss

Fixes #126 
Let me know what you think of the `+ 1` in the breakpoints. On dev now.

Slightly modifying the responsive tablet rules.

---

src/client/styles/components/_bookFilters.scss
src/client/styles/components/_filter.scss

Fixes #99 
Check it out on dev for tablet view.

Updating the clear filters button for tablet view.

---

src/client/styles/components/_hero.scss

Fixes #130 because stakeholders know best.
Up on dev.

Lets make h1 better and not plain

---

src/server/views/index.ejs

Adding html doctype

---

src/app/components/BookFilters/BookFilters.jsx

Testing removing `aria-live` and adding a short delay to the focus for better screenreader interaction.

Removing aria-live from filter list and delaying the focus to the # books found.

---

CHANGELOG.md
package.json

Formality PR to update docs and header version.

Integrate fundraising banner

---

CHANGELOG.md
package.json
src/server/views/index.ejs

This PR adds OptinMonster and updates header component to 2.4.7

Updated header to 2.4.7 and added OptinMonster.

---

appConfig.js
src/app/components/Application/Application.jsx
src/app/components/Hero/Hero.jsx
src/app/components/ListFilter/ListFilter.jsx
src/app/components/ListSelector/ListFilter.jsx
src/app/components/ListSelector/ListSelector.jsx
src/app/components/Sidebar/Sidebar.jsx
test/unit/ListFilter.test.js
test/unit/ListSelector.test.js

This PR focus on creating the basic form of creates  season dropdown menu. It adds a new component for the menu. It also adds some dummy data for running the apps and generate the dropdown menu.

Kp/www 72/create form for date input

---

src/app/components/ListSelector/ListSelector.jsx
test/unit/ListSelector.test.js

This PR adds new unit tests for testing the behaviors after an API request is made. Based on the results, the application should pass different data to BookStore.

Api unit tests

---

appConfig.js
platformConfig.js
src/app/actions/BookActions.js
src/app/components/Application/Main.jsx
src/app/components/Sidebar/Sidebar.jsx
src/app/stores/BookStore.js
src/app/utils/ModelListOptionsService.js
src/server/routes/monthData.js
test/unit/DateService.test.js
test/unit/ListFilter.test.js
test/unit/Main.test.js
test/unit/ModelListOptionsService.test.js
test/unit/Sidebar.test.js

This PR updates the functions to call for full available lists first before get the books. It maps the lists with correct season/month and year.

Fetch selector options

---

CHANGELOG.md
package.json
src/server/routes/monthData.js
test/unit/DateService.test.js
test/unit/ModelListOptionsService.test.js

This PR just updates the changes on CHANGELOG and bumps the version. It now points to `development` as the base, but it will wait until all other PRs to be merged, so it will then be merged to the latest `development`.
It also fixes some syntax issue that eslint complains.

Add changelog and version

---

appConfig.js
src/app/actions/BookActions.js
src/app/components/About/About.jsx
src/app/components/Application/Application.jsx
src/app/components/Application/Main.jsx
src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookList/BookList.jsx
src/app/components/BookPage/BookPage.jsx
src/app/components/ListSelector/ListSelector.jsx
src/app/components/Sidebar/Sidebar.jsx
src/app/stores/BookStore.js
src/client/styles/components/_bookList.scss
src/server/routes/annualData.js
src/server/routes/monthData.js
test/unit/Alt.test.js
test/unit/Application.test.js
test/unit/BookList.test.js
test/unit/BookPage.test.js
test/unit/ListSelector.test.js
test/unit/Main.test.js
test/unit/Sidebar.test.js

* Updating action call and store data structure for the app.
* Updating a few function names.
* Updating routing for the individual page.
* Updating variable names for fetching and returning data.
* Filtering picks by audience and by tag.
Initial PR but need to add tests.

Update dynamic tweaks

---

src/app/components/Application/Main.jsx
src/app/components/BookFilters/BookFilters.jsx
src/app/components/Sidebar/Sidebar.jsx
src/app/utils/utils.js
test/unit/Main.test.js
test/unit/utils.test.js

This PR should fix the problem of Filter by Tags not changing when a user switches `audience` within a `season` for `staff-picks`. Please review. Thanks!

Www 214 dynamic filters

---

appConfig.js
platformConfig.js
src/app/components/About/About.jsx
src/app/components/Application/Application.jsx
src/app/components/Application/Main.jsx
src/app/components/Book/Book.jsx
src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookList/BookList.jsx
src/app/components/BookPage/BookPage.jsx
src/app/components/Buttons/SimpleButton.jsx
src/app/components/ListSelector/ListFilter.jsx
src/app/components/ListSelector/ListSelector.jsx
src/app/components/ListTitle/ListTitle.jsx
src/app/components/Sidebar/Sidebar.jsx
src/app/utils/DateService.js
src/app/utils/ModelListOptionsService.js
src/app/utils/utils.js
src/server/routes/annualData.js
src/server/routes/monthData.js
src/server/routes/routes.js
src/server/routes/selectClientData.js
src/server/routes/selectData.js
test/unit/BookList.test.js
test/unit/DateService.test.js
test/unit/ListSelector.test.js
test/unit/ListTitle.test.js
test/unit/Main.test.js
test/unit/ModelListOptionsService.test.js

Adds routing, component, config and unit test changes for annual list rendering with the new selector component. There are probably unit test missing, so feel free to suggest what else needs coverage.

Annual lists updates

---

.gitignore
src/app/components/Book/Book.jsx
test/unit/Book.test.js

From `Staff Pick By: ...` to `Staff Pick by ...`.
JIRA: [WWW-263](https://jira.nypl.org/browse/WWW-263)

Updating the staff pick by line.

---

server.js
src/server/views/index.ejs

Updating the route to use the config's base url.

---

src/app/components/Error404Page/Error404Page.jsx
test/unit/Error404Page.test.js

The contents and link updates for the 404 page.
See the QA sheet, page 21
https://docs.google.com/document/d/1U7arU_AhbQptOQaWvcg4OZBVPfWT2CjTa46i2j1MkUw/edit?ts=5afca641

Update contents of 404

---

src/client/styles/components/_bookItem.scss

Small css update to fix non issue.

---

appConfig.js
src/app/components/About/About.jsx
src/app/components/Application/Main.jsx
src/app/components/Book/Book.jsx
src/app/components/BookFilters/BookFilters.jsx
src/app/components/BookFilters/Filter.jsx
src/app/components/BookList/BookList.jsx
src/app/components/ListSelector/ListSelector.jsx
src/app/components/Sidebar/Sidebar.jsx
src/app/utils/utils.js
test/unit/About.test.js

The list dropdowns were not correctly rendering the proper values. Updated them.
FYI @courtneymcgee .

Fixing GA events for list dropdowns.

---

src/app/utils/DateService.js
test/unit/DateService.test.js

Just in case the length of the date in the returned data is more than 7 characters in length, then update the regex. A check for possible bad user input in the spreadsheet.

Updating regex date pattern checker.

---

CHANGELOG.md
package.json

Updating the footer but also including an update to the header. On dev: http://staff-picks-development.us-east-1.elasticbeanstalk.com/books-music-movies/recommendations/best-books/staff-picks

Footer update

---

CHANGELOG.md
package.json
readme.md

This PR updates footer to v0.5.2 to add non-profit status information
https://jira.nypl.org/browse/SCC-1309

Bumped footer version to v0.5.2

---

.ebextensions/falcon_crowdstrike.config
CHANGELOG.md
package.json
readme.md

- Adding Falcon Crowdstrike sensor to operating system
- Changes reflect on README, CHANGELOG and package.json

SEB-1379 Upgrade to version 4.0.9
